backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  identity_url: "https://writeclub.ca/.netlify/identity"
  gateway_url: "https://writeclub.ca/.netlify/git"
  login: true
  roles: ["admin", "editor"] # Allow both admin and editor roles

media_folder: "assets/images/uploads" # Folder for uploaded images
public_folder: "/assets/images/uploads" # URL path for uploaded images

collections:
  - name: "authors"
    label: "Authors"
    folder: "_authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Display Name", name: "title", widget: "string" }
      - { label: "Username", name: "username", widget: "string" }
      - { label: "Default Author", name: "default", widget: "boolean", default: false }
      - { label: "Avatar", name: "image", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Facebook", name: "facebook", widget: "string", required: false }
      - { label: "GitHub", name: "github", widget: "string", required: false }
      - { label: "Reddit", name: "reddit", widget: "string", required: false }
      - { label: "Instagram", name: "instagram", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "Biography", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Sidebar", name: "sidebar", widget: "select", options: ["none", "left", "right"], default: "none" }
          - { label: "Content", name: "body", widget: "markdown" }
      
      # Additional pages can be added here following the same pattern
      - name: "terms"
        label: "Terms & Code of Conduct"
        file: "terms.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Sidebar", name: "sidebar", widget: "select", options: ["none", "left", "right"], default: "none" }
          - { label: "Content", name: "body", widget: "markdown" }

      - name: "events"
        label: "Events Page"
        file: "events.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Sidebar", name: "sidebar", widget: "select", options: ["none", "left", "right"], default: "none" }
          - { label: "Content", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", value_field: "username", search_fields: ["title", "username"], display_fields: ["title"] }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
